# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:9.6
    container_name: "db_pg"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
  web:
    build:
      context: . 
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
     - '4000:4000' 
    container_name: "iflab_warehouse"
    environment:
      PORT: 4000
    command: bash -c "npx prisma migrate dev && npm run dev"
    


volumes:
  db: